version: "3"
services:
  frontend:
    image: 663291012203.dkr.ecr.us-east-1.amazonaws.com/netflix_frontend:latest
    ports:
      - "80:80"
  backend:
    image: 663291012203.dkr.ecr.us-east-1.amazonaws.com/netflix_backend:latest
    ports:
      - "8080:8080"